//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gladkiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int ID { get; set; }
        public int Менеджер { get; set; }
        public decimal Junior__мин_ЗП_ { get; set; }
        public decimal Middle__мин_ЗП_ { get; set; }
        public decimal Senior__мин_ЗП_ { get; set; }
        public double Коэффициент_для_Анализ_и_проектирование { get; set; }
        public double Коэффициент_для_Установка_оборудования { get; set; }
        public double Коэффициент_для_Техническое_обслуживание_и_сопровождение { get; set; }
        public int Коэффициент_сложности { get; set; }
        public int Коэффициент_Времени { get; set; }
        public int Коэффициент_Денег { get; set; }
    
        public virtual Manager Manager { get; set; }
    }
}
